# This script was generated by OpenMM-MDL Setup on 2026-09-28.


#       ,-----.    .-------.     .-''-.  ,---.   .--.,---.    ,---.,---.    ,---. ______       .---.      
#     .'  .-,  '.  \  _(`)_ \  .'_ _   \ |    \  |  ||    \  /    ||    \  /    ||    _ `''.   | ,_|      
#    / ,-.|  \ _ \ | (_ o._)| / ( ` )   '|  ,  \ |  ||  ,  \/  ,  ||  ,  \/  ,  || _ | ) _  \,-./  )      
#   ;  \  '_ /  | :|  (_,_) /. (_ o _)  ||  |\_ \|  ||  |\_   /|  ||  |\_   /|  ||( ''_'  ) |\  '_ '`)    
#   |  _`,/ \ _/  ||   '-.-' |  (_,_)___||  _( )_\  ||  _( )_/ |  ||  _( )_/ |  || . (_) `. | > (_)  )    
#   : (  '\_/ \   ;|   |     '  \   .---.| (_ o _)  || (_ o _) |  || (_ o _) |  ||(_    ._) '(  .  .-'    
#    \ `"/  \  ) / |   |      \  `-'    /|  (_,_)\  ||  (_,_)  |  ||  (_,_)  |  ||  (_.\.' /  `-'`-'|___  
#     '. \_/``".'  /   )       \       / |  |    |  ||  |      |  ||  |      |  ||       .'    |        \ 
#       '-----'    `---'        `'-..-'  '--'    '--''--'      '--''--'      '--''-----'`      `--------` 
                                                                                                      
                                                                                                      

from openmmdl.openmmdl_simulation.scripts.forcefield_water import ff_selection, water_forcefield_selection, water_model_selection, generate_forcefield, generate_transitional_forcefield
from openmmdl.openmmdl_simulation.scripts.protein_ligand_prep import prepare_ligand, rdkit_to_openmm, merge_protein_and_ligand, water_padding_solvent_builder, water_absolute_solvent_builder, membrane_builder, water_conversion, write_ligand_with_partial_charges, solvate_topol_padding_openff, ptm_topology_from_pdb, solvate_topol_absolute_openff
from openmmdl.openmmdl_simulation.scripts.post_md_conversions import mdtraj_conversion, MDanalysis_conversion
from openmmdl.openmmdl_simulation.scripts.cleaning_procedures import cleanup_post_md, close_reporters, create_directory_if_not_exists, copy_file, organize_files, post_md_file_movement 

import simtk.openmm.app as app
from simtk.openmm.app import PDBFile, Modeller, PDBReporter, StateDataReporter, DCDReporter, CheckpointReporter, AmberPrmtopFile, AmberInpcrdFile
from simtk.openmm import unit, Platform, MonteCarloBarostat, LangevinMiddleIntegrator
from openff.pablo import ResidueDefinition, STD_CCD_CACHE, topology_from_pdb
from openff.toolkit import ForceField
from openff.interchange.components._packmol import (RHOMBIC_DODECAHEDRON, UNIT_CUBE, solvate_topology)
from openff.units import Quantity
from rdkit import Chem
from rdkit.Chem import rdCIPLabeler
from openff.toolkit import Molecule
from openmm.openmm import XmlSerializer
from simtk.openmm import Vec3
import simtk.openmm as mm
import pdbfixer
import numpy as np
from openmmtools.utils.equilibration import run_gentle_equilibration
import sys
import os
import shutil
import gc

# Input Files
############# Ligand and Protein Data ###################
########   Add the Ligand SDF File and Protein PDB File in the Folder with the Script  ######### 

protein = "3ip9_dye-processed_openMMDL-processed_openMMDL.pdb"
ligand = 'maleimide.sdf'
smallMoleculeForceField = None
smallMoleculeForceFieldVersion = None
RESname = 'CYS'
RESsmiles = '[C:10]-[S:1]-[H:2]'
LIGsmiles = '[H:4]-[C:6]([H:5])=[C:7]([N:8])-[C:9]'
PTMsmiles = '[N:3]1-[C:4](=[O:5])-[C:6](-[H:2])(-[H:11])-[C@:7](-[S:1]-[C:10])(-[H:12])-[C:8](=[O:9])-1'

############# PTM Residue Definition ####################################

LIGresdef = ResidueDefinition.anon_from_sdf(ligand)
RESresdef = STD_CCD_CACHE[RESname][0]
PTMresdef = ResidueDefinition.react(
    reactants=[RESresdef, LIGresdef],
    reactant_smarts=[
        RESsmiles,
        LIGsmiles,
    ],
    product_smarts=[
        PTMsmiles,
    ],
)[0][0]

############# Forcefield, Water and Membrane Model Selection ###################

ff = 'OPENFF3'
water = 'OPC3'

############# Water Box Settings ###################

add_membrane = False
Water_Box = "Buffer"
water_padding_distance = 1.0
water_boxShape = 'cube'
water_ionicstrength = 0.15
water_positive_ion = 'Na+'
water_negative_ion = 'Cl-'

# System Configuration

nonbondedMethod = app.PME
nonbondedCutoff = 1.0*unit.nanometers
ewaldErrorTolerance = 0.0005
constraints = app.HBonds
rigidWater = True
constraintTolerance = 0.000001
hydrogenMass = 1.5*unit.amu

# Integration Options

step_time = 0.002
dt = 0.002*unit.picoseconds
temperature = 300*unit.kelvin
friction = 1.0/unit.picosecond
pressure = 1.0*unit.atmospheres
barostatInterval = 25

# Simulation Options

sim_length = 50
steps = int(sim_length / step_time * 1000)
dcdFrames = 1000
dcdInterval = int(steps / dcdFrames)
pdbInterval_ns = 10
pdbInterval = int(steps * (pdbInterval_ns / sim_length))
platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'mixed'}
dcdReporter = DCDReporter('trajectory.dcd', dcdInterval)
dataReporter = StateDataReporter('log.txt', 1000, totalSteps=steps,
    step=True, speed=True, progress=True, potentialEnergy=True, temperature=True, separator='\t')
checkpointInterval = int(1000 * 0.02 / 0.002)
checkpointReporter = CheckpointReporter('checkpoint.chk', checkpointInterval)
checkpointReporter10 = CheckpointReporter('10x_checkpoint.chk', checkpointInterval* 10)
checkpointReporter100 = CheckpointReporter('100x_checkpoint.chk', checkpointInterval* 100)

print("Preparing PTM residue topology...")

topology_openff = ptm_topology_from_pdb(protein, PTMresdef)

topology_openff.box_vectors = None

if Water_Box == "Buffer":
    topology_openff = solvate_topol_padding_openff(
        topology_openff,
        water_padding_distance,
        water_boxShape,
        water_ionicstrength,
    )
elif Water_Box == "Absolute":
    topology_openff = solvate_topol_absolute_openff(
        topology_openff,
        water_box_x,
        water_box_y,
        water_box_z,
        water_ionicstrength,
    )

forcefield_selected = ff_selection(ff)
water_selected = water_forcefield_selection(water=water, forcefield_selection=ff_selection(ff))

sage_ff14sb = ForceField(forcefield_selected, water_selected)
interchange = sage_ff14sb.create_interchange(topology_openff)

# Prepare the Simulation

print('Building system...')
system = interchange.to_openmm_system(hydrogen_mass=hydrogenMass.value_in_unit(unit.amu), ewald_tolerance=ewaldErrorTolerance)
topology = interchange.to_openmm_topology()
for residue in topology.residues():
    residue.id = str(residue.id)
positions = interchange.positions.to_openmm()
positions_for_equil = np.array(positions.value_in_unit(unit.nanometers)) * unit.nanometers
write_ligand_with_partial_charges(topology, system, positions, ligand_name=globals().get('ligand_name'), ligand_names=globals().get('ligand_names'), ligand_files=globals().get('ligands'))
system.addForce(MonteCarloBarostat(pressure, temperature, barostatInterval))
integrator = LangevinMiddleIntegrator(temperature, friction, dt)
integrator.setConstraintTolerance(constraintTolerance)
simulation = app.Simulation(topology, system, integrator, platform, platformProperties)
simulation.context.setPositions(positions)

# Minimize and Equilibrate


equil_output = f"Equilibration_{os.path.splitext(os.path.basename(protein))[0]}.pdb"
                          
print('Performing minimization and equilibration...')

stages = [
    {
        # Minimize with full protein restraint.
        "EOM": "minimize",
        "n_steps": 10000,
        "temperature": temperature,
        "ensemble": None,
        "restraint_selection": "protein and not type H",
        "force_constant": 4.0,
        "collision_rate": 1,
        "timestep": 2 * unit.femtoseconds,
    },
    {
        # Heat from 100 K to 300 K under NVT.
        # High collision rate damps velocity chaos during heating.
        "EOM": "MD_interpolate",
        "n_steps": 50000,
        "temperature": 100 * unit.kelvin,
        "temperature_end": temperature,
        "ensemble": "NVT",
        "restraint_selection": "protein and not type H",
        "force_constant": 4.0,
        "collision_rate": 10,
        "timestep": 2 * unit.femtoseconds,
    },
    {
        # NPT, full protein restraint.
        # Box volume and membrane area start adjusting.
        "EOM": "MD",
        "n_steps": 62500,
        "temperature": temperature,
        "ensemble": "NPT",
        "restraint_selection": "protein and not type H",
        "force_constant": 4.0,
        "collision_rate": 5,
        "timestep": 2 * unit.femtoseconds,
    },
    {
        # NPT, backbone only at half FC.
        "EOM": "MD",
        "n_steps": 62500,
        "temperature": temperature,
        "ensemble": "NPT",
        "restraint_selection": "protein and backbone and not type H",
        "force_constant": 4.0 / 2,
        "collision_rate": 2,
        "timestep": 2 * unit.femtoseconds,
    },
    {
        # NPT, backbone very loose.
        "EOM": "MD",
        "n_steps": 250000,
        "temperature": temperature,
        "ensemble": "NPT",
        "restraint_selection": "protein and backbone and not type H",
        "force_constant": 4.0 / 10,
        "collision_rate": 1,
        "timestep": 2 * unit.femtoseconds,
    },
]
            
run_gentle_equilibration(
    topology,
    positions_for_equil,
    system,
    stages,
    equil_output,
    platform_name = 'CUDA',
)
positions = PDBFile(equil_output).positions

# Simulate

print('Simulating...')
integrator = LangevinMiddleIntegrator(temperature, friction, dt)
integrator.setConstraintTolerance(constraintTolerance)
simulation = app.Simulation(topology, system, integrator, platform, platformProperties)
simulation.context.setPositions(positions)
simulation.reporters.append(PDBReporter(f'output_{protein}', pdbInterval))
simulation.reporters.append(dcdReporter)
simulation.reporters.append(dataReporter)
simulation.reporters.append(checkpointReporter)
simulation.reporters.append(checkpointReporter10)
simulation.reporters.append(checkpointReporter100)
simulation.reporters.append(StateDataReporter(sys.stdout, 1000, step=True, potentialEnergy=True, temperature=True))
simulation.currentStep = 0
simulation.step(steps)
close_reporters(simulation)
del simulation
gc.collect()
mdtraj_conversion(f'Equilibration_{protein}', 'mdtraj_pdb_dcd')
MDanalysis_conversion('centered_old_coordinates_top.pdb', 'centered_old_coordinates.dcd', mda_output='mda_pdb_dcd', output_selection='mda_prot_lig_all')
post_md_file_movement(protein, mda_selection='mda_prot_lig_all')